name: 公司上班下班签到

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 8,18 * * 1-5'
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2
    - name: 初始化Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: 签到
      run: |
        pip install -r requirements.txt

        corpid='${{ secrets.CORPID }}'
        secret='${{ secrets.SECRET }}'
        agentid='${{ secrets.AGENTID}}'
        toparty='${{ secrets.TOPARTY}}'

        user='${{ secrets.USER }}'
        pwd='${{ secrets.PASSWD }}'
        dev='${{ secrets.LOGIN_DEV }}'
        
        user_list=()
        pwd_list=()
        dev_list=()
        IFS="#"
        for u in ${user[*]}
        do
        user_list[${#user_list[*]}]=${u}
        done
        for p in ${pwd[*]}
        do
        pwd_list[${#pwd_list[*]}]=${p}
        done
        for d in ${dev[*]}
        do
        pwd_list[${#dev_list[*]}]=${d}
        done
        user_num=${#user_list[*]}
        pwd_num=${#pwd_list[*]}
        dev_num=${#dev_list[*]}
        if [[ $user_num != $pwd_num || $user_num != $dev_num ]];then
        echo "账号和密码、设备个数不对应"
        exit 1
        else
        echo "共有 $user_num 个账号，即将开始签到"
        fi
        for ((i=0;i<$user_num;i++))
        do
        python3 checkin.py <<EOF
        ${corpid}
        ${secret}
        ${agentid}
        ${toparty}
        ${user_list[$i]}
        ${pwd_list[$i]}
        ${dev_list[$i]}
        EOF
        done
